config/routes.rb
Ebime::Application.routes.draw do
  root 'sessions#new'
  resources :sessions,      only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get',    as: 'signin'
  match '/kintai',  to: 'kintais#index',        via: 'get',    as: 'kintai'
  match '/kintai',  to: 'kintais#index',        via: 'post'
  match '/jisseki', to: 'jissekis#index',       via: 'get',    as: 'jisseki'
  match '/jisseki', to: 'jissekis#index',       via: 'post'
  match '/project', to: 'projects#index',       via: 'get',    as: 'project'
  match '/project', to: 'projects#update',      via: 'patch'
  match '/project', to: 'projects#destroy',     via: 'delete'
  resources :projects,      only: [:create]
  match '/assign',  to: 'user_projects#index',  via: 'get',    as: 'assign'
  resources :user_projects,      only: [:create, :update]  
  match '/approval',to: 'approval#index',       via: 'get',    as: 'approval'
  match '/approval',to: 'approval#index',       via: 'post'
  # match '/approval', to: 's#index',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete', as: 'signout'
  #resources :users
end

app/controllers/approval_controller.rb
class ApprovalController < ApplicationController
  before_action :signed_in_user

  def index
    #ユーザ一覧用
    @followed_user = Relationship.where("followed_id = ?", @current_user.id)
    @user_name = []
    @followed_user.each do |u|
      @user_name << User.find(u.follower_id).name
    end
    @target_year = ["2014","2015","2016",]
    @target_month = ["1","2","3","4","5","6","7","8","9","10","11","12"]
    
    #実績用
    if params[:user] && params[:year] && params[:month]
      user = params[:user] 
      year = params[:year]
      month = params[:month]
      date = Time.parse("#{year}/#{month}")
      @jisseki_param = [user, date]
    
      user_project = UserProject.where("user_id = ?", User.find_by_name(user).id)
      @jisseki = Jisseki.order("date").where("user_project_id IN (?) AND date BETWEEN ? AND ?", user_project.ids, date.beginning_of_month, date.end_of_month )
    end

    if params[:approval_]
      @user = user__params[:value]
    end

    if params[:remand_]
      raise "error"
    end

  end
  
  private

    def user__params
      params.require(:user_).permit(:value)
    end

    def month__params
      params.require(:month_).permit(:value)
    end

end

app/helpers/approval_helper.rb
module ApprovalHelper
end

app/views/approval/index.html.erb
<% provide(:title, '承認') %>

<div id="approval">

  <div class="row">
    <div class="col-md-3"></div>
    <div class="title col-md-3"><p>承認</p></div>
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
  </div><!-- row -->

  <div class="row">
    <%= form_tag(approval_path, method: "get") do %>
      <div class="user col-md-4">
        <p>ユーザ選択</p>
        <%= select_tag 'user', options_for_select(@user_name) %>        
      </div>
      <div class="month col-md-4">
        <p>対象年月</p>
        <%= select_tag 'year',  options_for_select(@target_year) %>
        <%= select_tag 'month', options_for_select(@target_month) %>
      </div>
      <div class="approval col-md-4">
        <p>実績検索</p>
        <%= submit_tag "検索", name: "jisseki", class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="jisseki">
      <p>実績一覧</p>
      
      <% if @jisseki_param.present? %>
        <div class="param">
          <p>ユーザ ： <%= @jisseki_param[0] %></p>
          <p>選択月 ： <%= @jisseki_param[1].strftime("%Y/%m") %></p>
        </div>

        <% if @jisseki.blank? %>
          <div class="none"><p>選択月には実績が存在しません。</p></div>

        <% else %>
          <div class="approval_remand">
              <%= form_tag(approval_path, method: "post") do %>
              <%= hidden_field :user_, value: @jisseki_param[0] %>
              <%= hidden_field :month_, value: @jisseki_param[1] %>
              <%= submit_tag "承認", name: "approval_", class: "btn btn-lg btn-primary" %>
              <%= submit_tag "差戻", name: "remand_", class: "btn btn-lg btn-warning" %>
            <% end %>
          </div>

            <div id="slider">
              <div id="door">
                <% @jisseki.each do |j| %>
                  <div class="date">
                    <div class="day"><%= j.date.strftime("%m/%d") %></div>
                    <div class="project"><%= Project.find(UserProject.find(j.user_project_id).project_id).name %></div>
                    <div class="time"><%= j.time.to_s %>h</div>
                  </div>
                <% end %>
              </div><!-- #door -->
            </div><!-- #slider -->
          <% end %>
        <% end %>
      </div><!-- jisseki -->
    </div><!-- row -->

</div>